services:
  backend:
    build: ./backend
    container_name: gnn_backend
    ports:
      - "8001:8001"
    environment:
      - ENV=development
    depends_on:
      - gnn_inference
    volumes:
      - ./data/m100_aggregated:/data      # Mount data directory
      - ./logs:/app/logs                  # Mount logs directory
      # - ./storage:/app/storage
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "8502:8502"
    depends_on:
      - backend
    volumes:
      - ./data/m100_aggregated:/data  # mount as /data
  gnn_inference:
    build:
      context: ./gnn_inference
    container_name: gnn_inference
    ports:
      - "10000:10000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./gnn_inference/GNN_models:/app/GNN_models     # Mount models from host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]